apiVersion: v1
kind: Service

metadata:
  name: app-haskell-service

spec:
  selector:
    app: app-haskell
  ports:
    - protocol: TCP
      name: web-app
      port: 8080
    - protocol: TCP
      name: web-app-metrics
      port: 8081
  type: LoadBalancer
