version: "3.9"

x-logging: &logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: "5m"
    max-file: "10"

x-healthcheck: &healthcheck
  interval: 20s
  timeout: 10s

services:
  grafana:
    image: grafana/grafana:9.1.8-ubuntu
    mem_limit: 100m
    volumes:
      - grafana-data:/var/lib/grafana
      - ${PWD}/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:3000/api/health || exit 1"]
      <<: *healthcheck

  promtail:
    image: grafana/promtail:2.6.1
    mem_limit: 100m
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/config/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
    command:
      - "-config.file=/etc/promtail/promtail.yml"
    restart: unless-stopped
    networks:
      - app_haskell
      - app_python
      - monitoring
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9080' || exit 1"]
      <<: *healthcheck

  loki:
    image: grafana/loki:2.6.1
    mem_limit: 100m
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki/
      - ${PWD}/config/loki/loki-config.yml:/etc/loki-config.yml:ro
    command: -config.file=/etc/loki-config.yml
    restart: unless-stopped
    networks:
      - monitoring
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:3100/ready || exit 1"]
      <<: *healthcheck

  prometheus:
    image: prom/prometheus:v2.27.0
    mem_limit: 100m
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--log.level=debug'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--query.lookback-delta=30s'
    restart: unless-stopped
    networks:
      - app_python
      - app_haskell
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:9090/-/healthy || exit 1"]
      <<: *healthcheck

  app_python:
    image: grommash99/moscow-time-py:latest
    mem_limit: 100m
    ports:
      - "8080:8080"
    networks:
      - app_python
      - monitoring
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:8080/health || exit 1"]
      <<: *healthcheck
    volumes:
      - app-python-data:/app/data

  app_haskell:
    image: grommash99/moscow-time-hs:latest
    mem_limit: 100m
    ports:
      - "8082:8080"
      - "8081:8081"
    networks:
      - app_haskell
      - monitoring
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:8080/health || exit 1"]
      <<: *healthcheck
    volumes:
      - app-haskell-data:/app/data

networks:
  app_python:
  app_haskell:
  monitoring:

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  prometheus-data:
  app-python-data:
  app-haskell-data:
