apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-haskell-chart.fullname" . }}-config
  labels:
    {{- include "app-haskell-chart.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" | nindent 4 }}
