apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-haskell-chart.fullname" . }}
  labels:
    {{- include "app-haskell-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: http
    - port: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
      targetPort: metrics
  selector:
    {{- include "app-haskell-chart.selectorLabels" . | nindent 4 }}
