name: app-haskell
version: 0.1.0.0
author: "Abuzyar Tazetdinov"
maintainer: "tazetdinov9925@gmail.com"

extra-source-files:
  - README.md

description: Simple web application which shows current time in Moscow.

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

default-extensions:
  - OverloadedStrings

ghc-options:
  - -Wall
  - -fno-warn-type-defaults
  - -fwrite-ide-info
  - -hiedir=.hie

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - servant
  - servant-server
  - servant-lucid
  - lucid
  - warp
  - data-default
  - unliftio
  - time

library:
  source-dirs: src

executables:
  app-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
    dependencies:
      - app-haskell

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - app-haskell
      - hspec
      - HUnit
      - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
      - Glob
      - QuickCheck
      - template-haskell
