resolver: lts-18.28

allow-newer: true

packages:
  - .

extra-deps:
  - co-log-0.4.0.1
  - servant-lucid-0.9.0.5
  - tz-0.1.3.6
  - name: servant-prometheus
    git: https://github.com/serokell/servant-prometheus
    commit: 3a6414f68c3c5f3e3516fdb969545811b8df160c
