# all linter checks run from pre-commit,
# no duplication of checking policies in .pre-commit-config.yaml and CI

name: pre-commit

on:
  pull_request:
  push:
    branches:
      - "lab**"
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
