# all linter checks run from pre-commit,
# no duplication of checking policies in .pre-commit-config.yaml and CI

name: pre-commit

on:
  pull_request:
  push:
    branches:
      - "lab**"
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stylish-haskell
        run: |
          ./scripts/download-stylish-haskell.sh
          chmod +x ./stylish-haskell
          mv ./stylish-haskell /usr/local/bin/

      - name: Install hlint
        run: ./scripts/download-hlint.sh

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0
