# all linter checks run from pre-commit,
# no duplication of checking policies in .pre-commit-config.yaml and CI

name: pre-commit

on:
  pull_request:
  push:
    branches:
      - "lab**"
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install stylish-haskell
        run: |
          ./scripts/download-latest-stylish-haskell.sh
          chmod +x ./stylish-haskell
          mv ./stylish-haskell /usr/local/bin/

      - name: Install hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh > hlint
          chmod +x ./hlint
          mv ./hlint /usr/local/bin/

      - uses: pre-commit/action@v3.0.0
